# R
研究者がよく使っている無料分析ソフトの１つ。現代の動物行動学、動物生態学において不可欠かつ基本的なツール。本章はWindowsでの説明に限定していることに注意。

## なぜRを使うのか？
「創造的人生の持ち時間は10年だ」（映画『風立ちぬ』、宮崎駿監督）

このセリフは、研究者もそうかもしれないと思うと心に刺さる。フィールド調査の時間が十全にある学生時代に行ったフィールドでの印象や観察データが、知識や技能がないばかりに宝の持ち腐れになるのはもったいない。

Rは知識や技能の蓄積をすることができ、備忘録としての役割を果たしてくれる。特に備忘録としての機能を果たしてくれるのが後述するRMarkdownである。自分が何をしたのかを振り返ることができるということは再現性にも関わる。

## How to R
インストールなどの初期設定は次節以降扱う。<br>
本節では、前処理や結果の出力の勉強について紹介する。<br>
とにかく、便利さを実感してRと友達になろう。


- [わたしたちのR](https://www.jaysong.net/RBook/):
ざっくり勉強するのによさそうなサイト。
- [The R Graph Gallery](https://r-graph-gallery.com/index.html): Rで作図するときに重宝するサイト。

Rの本は実は英語で無料公開されていることが多い。非常にありがたい。ネット上のものは常に更新されているため、本と内容が違うことがある。

- [R for data science](https://r4ds.had.co.nz/):
邦訳『Rではじめるデータサイエンス』のサイト。

- [R Graphic Cookbook](https://r-graphics.org/):
邦訳『Rグラフィックスクックブック』のサイト。

- [R Markdown Cookbook](https://gedevan-aleksizde.github.io/rmarkdown-cookbook/):
この本はなんと日本語で読める。

## R・RStudio・Rtoolsのインストール
R本体をインストールし、RStudioもインストールする。以下のリンクからインストールできる。
https://posit.co/download/rstudio-desktop/

### 言語設定の確認
言語設定によっては日本語がバグの原因となり、日本語の部分が後で何を書いたのかわからなくなる。
必ずUTF-8にすること。UTF-8で指定しないとコードの日本語がすべて文字化けしてしまう(T_T)<br>
設定方法は、

Tools > Global Options > Code > Saving

と進み、真ん中にあるDefault text encoddingでUTF-8を指定。

## Rmarkdownの作成
Rで研究を始めるなら、RファイルではなくRmdファイルにすることを強く勧める。その理由として、結果とその結果に対する自分のコメントを書けることが大きい。

Wordで書くと容量が大きい文書ファイルをサクサク書けるうえ、$\LaTeX$と異なりPDFのみならずワードに変換したり、html形式に変換してネットで公開する等、応用可能性が広いのが特徴。
初期設定ではSourceペインに結果が表示されてしまう。これが嫌な人は、

Tools > Global Options > R Markdown > Basics

と進み、真ん中あたりの"Show output inline for all RMarkdown documents"のチェックを外すと解決する。
 

## 文献整理のテンプレート
拙著が「[修士のススメ](https://tabutan.github.io/GetStartedMaster/)」というウェブサイトで、Rmarkdownの作り方と使い方を紹介している。
Rmarkdownで論文備忘録を作ることを推奨している。

## GitHub
コードの公開などで一般によく使われている。ここにファイルを保存することでバージョン管理を行うことができ、内容変更のたびにバックアップ用にファイルを作る必要がなくなる。

<!-- ### GitHubアカウントの作成 -->

<!-- ### Gitソフトウェアのインストール -->

<!-- ### リポジトリ－の作成 -->


<!-- ### commmit & push -->
<!-- コメントを付けてコミットし、その後プッシュすることでGitHubに保存される。 -->

<!-- ### pull -->
<!-- GitHubに保存したファイルをPCに取り込む。 -->

### Gitbookの公開
GitHub上でプロジェクトのページにある歯車のSettingsをクリック、左側にあるPagesに進む。

Build and deploymentのSourceをDeploy from a branchに設定し、Branchをmain, /docs（index.Rmdのoutput_dirで指定したもの）に設定。ページを更新するとBuild and deploymentの上に**Your site is alive at** https://XXXXXXと表示される。

その横にあるVisit siteをクリックし、そのURLを取得できる。



