# はじめに
論文との接し方がわからない…<br>

初めて論文を読むときに戸惑う人は多いだろう。<br>
お堅い、特殊な文章表現、、、<br>
諸々のことが論文を読むと降ってくる。
論文を読むとき、独学でおいそれと簡単に理解できる人は少数だろう。<br>

筆者は、論文という生き物の生態がわからず、もがき、苦悩した。<br>
研究というのがわかってきたのは修士論文を書き終わってから。<br>
遅きに失したというには遅すぎるくらい論文には苦労した。

**最初は何だって難しい**。<br>

最初の困難を乗り越えるのに多大な労力がいることを覚悟しよう。<br>
それでも心が折れかけるのは世の常。<br>
そんな迷える人が1人でもいち早く脱出し、研究の本分である考える時間を少しでも増やすことができるよう、論文をあまり読んだことがないために、論文の探し方、読み方を周りの人がどうしているのか知りたい人を対象にしている。

どんな高出力のエンジンを積んでいても進む方向がわからなければ、水の泡。<br>
力の効率：$\cos\theta$<br>
の$\theta$が0にできるだけ近づける、研究者の卵にとっての滑走路がこのサイトであれば、さいわいです。

# 論文の探し方
## 論文検索用エンジン
今日主流となっている論文の探し方は、ネット検索。たとえば、以下のものがある（筆者はもっぱらGoogle Scholar）。<br>

- Google Scholar
- Web of Science
- PubMed

以下、説明する際はGoogle Scholarであることをご容赦下さい。

## 検索方法
自分の興味・関心のあるキーワードを英語で知る必要がある。<br>
これがわからないと検索はただただ苦痛。<br>
キーワードは、教科書や本の章タイトル、レビュー論文からかいつまんでいくと見つかる可能性が高まるだろう。

### 芋づる式
どの論文でも引用されていることが多い。
新しめでよく引用されている論文から読むと効率がいいだろう。

### レビューを探す
検索時に、キーワードとともに"review"と打って検索するとレビュー論文がヒットしやすい。<br>
レビュー論文はそれまでのまとめであり。将来の展望について筆者が意見する論文である。本の場合、身内の論文ばかり引用していることがあるので注意が必要。

特集号が組まれていることがあるので、そこで一挙に情報収集できる可能性もある。

### 和文で探す
意外と穴場になるのが和文論文である。<br>
各学会の〇〇賞受賞者が記念レビュー論文を書いているので、非常に参考になることが多い。

## 論文アラート
### 出版社のサイトからアラート
自分の研究分野の論文はとにかくアラート。<br>
霊長類学の分野で言うと、以下の雑誌をアラートすれば英文は最新動向を大方把握できる。

- *Primates*
- *American Journal of Primatology*
- *International Journal of Primatology*
- *American Journal of Biological Anthropology*
- *Foria Primatologica*

#### お気に入り登録
気になる雑誌を出している出版社をまずお気に入りバーに登録しよう。
論文検索用のブラウザーを作ると他とゴチャゴチャしなくて済むのでおすすめ。

#### 雑誌の登録
面倒くさいが登録すると後々らく。

### 自分で設定したキーワードでアラート
例えば、"gorilla"をキーワード登録すると"gorilla"に引っかかる論文がアラートされる。
だが、しかし、思わぬ結果として霊長類のゴリラに関する論文よりむしろゴリラガラスに関する論文が山のように降ってくるので、キーワード登録には工夫がいる。

強そうに思われたいなら、マッチョガラスじゃだめですか？

### アラート時の小技
#### 論文用のメールアドレスを作る

# 論文の読み方
## 論文の構成から理解する

論文は、

1. **タイトル**: 究極の要約といっていい。

2. **要旨**: 自分の興味に合うのかのマッチングを行う文章。

3. **キーワード**: 論文検索時の大きな手掛かり。

4. **序論**: 論文で扱う分野のこれまでの経緯・著者の目的やモチベーションについて書かれている。

5. **方法**: 研究目的（or リサーチクエスチョン）を明らかにするためにおこなった調査方法・実験方法。

6. **結果**: 調査・実験結果

7. **考察**: 結果の解釈。

8. **結論**: 論文で伝えたい要点

から構成されている。<br>


研究者の卵は、まず自身が取り組む研究分野の枠組みを把握するために、要旨・序論・結論をあたり、多くの論文を読もう。<br>
50-100本ほど論文を読むと吸収する知識量が少なくなり、漸近線が見えてくるはず。<br>
論文丸々一本精読する義理は全くないし、読む必要がある論文はごく少数。

# 論文の記録方法
論文は一生かけても読み切れない。それくらい膨大な論文数が日々生まれている。<br>
記録方法は何でもいいが、キャッシュ＆フローのキャッシュを増やすことが研究を行う上で必要不可欠。<br>
誰だって忘れてしまう、忘れるようになってしまう。<br>
いや、忘れることは悪いことではない。外山滋比古が言うように積極的に忘れて思考を整理しよう [@toyama1986]。<br>

**論文の情報をアウトソーシングすることで、頭の中に発想する空間をつくろう**。<br>



## 論文管理ソフト
論文を自分のPCにPDFで保存するだけではなかなか効率が悪い。
忘れたときの備忘録をつくることは研究上必須能力である。
論文管理ソフトには以下のようなものがある。どのソフトでもタブレットとPCの情報を同期できる。特に、タブレットで手書き入力できるのはありがたい。

- Mendeley
- EndNote
- PaperPile


## 研究ノート
筆者は捨て紙の裏にメモを書いていてよくなくすタイプだった。<br>
こんな書類を管理できない人には研究ノートをお勧めする。筆者は研究だけでなく、日常生活のことも含めてすべてを書き込む「なんでもノート」を使うようになってから、ノイローゼの症状が緩和され、目の前の研究に取り組めるようになった（それでもノイローゼぽくなることはあるが全然マシ）。

とにかく頭がモヤモヤしたらこのノートに全部書いてみる。<br>
そしたら、頭がスカッとすることが案外多い。

後々繰り返し見返す内容はNotionとか別の電子メモに書くことですぐに検索できるようにすると、検索ストレスがなく研究に取り組める。

**参考情報**

筆者が愛用しているなんでもノートはこれ↓↓<br>
ミドリノートMDノートA5方眼罫

なんでもノートを作るきっかけになった動画
河野玄斗

## RMarkdown
筆者は、この文章をRmarkdownで作成している。筆者にとってRmarkdownは使い勝手がよく、使っていなかった時と比べて研究遂行スピードが上がったことを実感している。<br>
Rmarkdownは言うなれば、アイデアという溢れる湧き水をためてくれる記憶の栓でいてくれることで、忘れて思い出せないというブレーキを踏むことなく研究を進められる。

### R・RStudioのインストール
R本体をインストールし、RStudioもインストールする。以下のリンクからインストールできる。

#### 言語設定の確認
言語設定によっては日本語がバグの原因となり、日本語の部分が後で何を書いたのかわからなくなる。
必ずUTF-8にすること。

### Rmarkdownの作成


### 文献整理のテンプレート
テンプレートを作成した。
以下のリンクからアクセスしてファイルをコピペすれば、RStudioで文献調査の体制は整った。

- Rmdファイル
- bibファイル
- ymlファイル

### GitHub
コードの公開などで一般によく使われている。ここにファイルを保存することでバージョン管理を行うことができ、日付が変わるたびにファイルを作る必要がなくなる。

#### アカウントの作成

#### リポジトリ－の作成


#### commmit & push
コメントを付けてコミットし、その後プッシュすることでGitHubに保存される。

#### pull
GitHubに保存したファイルをPCに取り込む。







# 引用文献

