# 調査地での安全対策
身の安全確保は調査での最重要ミッションである。<br>
筆者がヤクザル調査隊^a^でよく言われたのは、

- 一に安全
- 二にデータ
- 三に楽しいこと

である。<br>
データより安全が何よりも優先されることを肝に銘じよう。<br>

フィールワークでも安全対策については日本生態学会が定期的に情報を更新している和文論文[@esj2019]がある。
全般的な安全対策については日本生態学会の和文論文に譲り、本章では特に和文論文では紹介されていない、動物を追跡するフィールドワークを必要とする研究者が、**事故予防の観点から**安全対策を行う際の必須項目について取り上げる。<br>

事故を起こさないことが何よりも重要である。しかし、山を歩いていれば小さな怪我はつきもの。そのような小さな怪我でもどのような状況で怪我したのか周りの人と情報共有することが周りの人の安全だけでなく、自分の安全にもつながる。

---

a. ヤクザル調査隊：屋久島の中腹部で行われているニホンザルの調査。毎年全国の大学生がボランティアで参加する。

## 山歩き
フィールドワークは体が資本の研究である。そのため、山を歩ける心身ともに健康な状態であることは研究をする上での第一条件になる。しかし、山を歩けることよりも大事なことは、

- ケガや事故を起こすイメージをもてること

である。
これができるのかどうかを確認する簡単な方法は、自転車・バイク・車の運転である。車の運転で事故を起こしやすい人はフィールドワークでも事故を起こしやすいのではないか、と自戒し今一度確認してほしい。<br>
その理由として、

1. 大丈夫、大丈夫と楽観的な判断をする
1. 自分の判断に自信がない（すぐに他人の判断を仰ぐ、頼る）
1. 周辺情報を見落としている（視野が狭い）

ことなどが挙げられる。
自分だけしっかりできていても、相手がいて周辺状況が常に変わるような環境では警戒心を持ちつつ心に余裕がないといけない。これは街中であろうが山の中だろうが変わらない。<br>
生きるための必須能力である。

### 疲れない歩き方
山歩きの時は腕を振らない。これはまさに「[ナンバ歩き](https://www.youtube.com/watch?v=gsUzpJNtl3M)[@nambawalk]」と呼ばれている歩き方である。へその下あたりにあると言われる丹田を意識した体の重心がぶれない歩き方は筋肉を使うことなく、疲れない歩き方である。

登山での疲れない歩き方について、日本山岳協会公認山岳ガイドの内田修市氏が非常にわかりやすく説明している。ここでもやはり基本は、丹田であり、重心をブレさないことである。


[登山実践講座2：登りの基本](https://youtu.be/wxiA6ZT-JrI)[@yamatabilesson2]<br>
[登山実践講座3：下りの基本](https://youtu.be/e2ExIhIiM4I)[@yamatabilesson3]<br>
[登山実践講座4：階段の上り下り](https://youtu.be/Bd4M1b-Yx_w)[@yamatabilesson4]<br>
[登山実践講座5：楽な段差の上り下り](https://youtu.be/-4_qGphpVmw)[@yamatabilesson5]<br>

### けがをしないようにするには 

身体の動きは筋骨格系と神経系の連動が大切になる。これを考える際にハンマー投げの室伏広治氏の考えが参考になるかもしれない。 

<!-- 彼の考えによると、身体を十分に発揮するには  -->

<!-- 1. 解剖学的身体（筋・骨格系）：車体  -->
<!-- 1. 機能（可動性）：ハンドル  -->
<!-- 1. ムーブメント（脳・中枢神経）：ドライバー  -->

<!-- この３つが重要と説く。  -->
<!-- けがをしないようにするために最重要視していたのが、ムーブメント（脳・中枢神経系）である。  -->

自分の身体の状態を確認する「セルフチェック」の項目と動画が公開されている（[室伏広治の身体診断「セルフチェック＋改善動画」](https://www.mext.go.jp/sports/b_menu/sports/jsa_00040.html)）。自分の身体のどこに柔軟性が欠けているのかを確認し、どういうけがをしやすい状態なのかを把握することはけが防止の第一歩。

[室伏広治の個人サイト](https://kojimurofushi.net/)もあり、新聞紙や紙風船を使った[トレーニング](https://kojimurofushi.net/rt_category/training/)等自身の研究成果について紹介している。室伏広治氏はランダムな動きを取り入れ、毎回同じ筋骨格系と神経系が使われないように工夫することで、身体能力の向上を考案しようと模索している。

### 靴紐の結び方
山歩きでは思わぬところで紐が横枝に引っかかってしまい転倒、最悪の場合滑落の可能性もある。靴紐ひとつとっても身の安全に直結する。<br>

**靴紐の安全対策**

- ひもの輪っかを出さず、靴の中に入れる
- スパッツ（ゲイター）を履いて、ひもの輪っかを隠す
- 靴ひもが緩まない結び方をする

自分に合った緩まない靴紐の結び方をひとつマスターしよう。
以下のサイトや動画が参考になるだろう。

[登山実践講座1：靴の履き方](https://youtu.be/QSFR22tfc2g)[@yamatabilesson1]<br>
[YouTube: 輪舞曲鈴の庭](https://www.youtube.com/watch?v=ysTBZLLanfg)[@rinbukyokurin]<br>
[Website: 山旅旅](https://yamatabitabi.com/archives/151957/)[@yamatabitabi] <br>

### 登山靴の選び方
登山靴はメーカーや同じメーカーでもシリーズによって形がまったく違う。足の形は人それぞれなので、とにかくいろいろ試し履きして合う靴を探すしかない。筆者は偏平足で足先が広めだったので、mont-bellは合わず、ZamberlanやScarpaに行きついた。

--- 


1. 足の角に当たらない靴を選ぶ<br>
隙間がなく足にピッタリ沿う靴がベスト。高さは中敷きで調節可能。革の登山靴以外は運動靴みたいになじむことはないので、最初がダメなら後もダメ。
1. 下り坂でつま先が当たらない靴を選ぶ<br>
登山店には必ず下り坂があるので、そこで足踏みしてつま先が当たらないことを確認する
1. ミドルカットの靴を選ぶ<br>
何もわからないならミドルカットの登山靴を選ぼう。
メリットとしては、
  - 足首を支えてくれる
  - 砂・泥除けでスパッツを履く場合などにも必要な高さ
1. メッシュの登山靴は選ばない<br>
岩場を歩いているとあっという間にメッシュの部分から破れてしまう。こうなってしまうと、防水機能も発揮してくれず使い物にならない。



## 地図読み
山の中は圏外なので、地図読みは生死に直結する能力の一つであり、フィールドワークで必ず身につけなければならない。<br>
注意してほしいのは、地図を過信しないこと。2万5千分の1の地図で一見危険でなさそうな場所でも、現場に行くと危険な場所がある。

[山と渓谷オンライン](https://www.yamakei-online.com/yama-ya/detail.php?id=2335)[@yamatokeikoku_dokuzu]で読図の説明があるので、地図の読み方がわからない人は一読するとよい。

### 地形図
まずはパソコンやタブレットで国土地理院の地図を見よう[[click here]](https://maps.gsi.go.jp/#5/36.104611/140.084556/&base=std&ls=std&disp=1&vs=c1g1j0h0k0l0u0t0z0r0s0m0f1)。
最近の電子地図は山の地形がわかりやすいように影がついている。影がついていなくても地図を見て立体視できるように慣れておこう。

### GPS
調査ではGarmin社製のGPSロガーがよく使われる。<br>
よく使われるPosition formatは”UTM UPS”、Map datumは”WGS84”。Tracksは、日々の遊動域の確認で使いやすいように、Advanced Setup ＞ Auto Archiveと進み、Dailyを選択すると便利。Recording Intervalは1分くらいにすると滑らかな移動経路が地図に現れる。数分おきだと急に移動するときに汚く表示される。この間隔に関しては自身の調査計画と見た目の感覚による。

## 天気
調査中は夜翌日の天気、朝に当日の天気を確認する。山の天気は変わりやすく、雨は低体温症の原因になる。調査中雨具は携行するほうがよい。

<!-- ### 天気図の読み取り -->


### 天気予報サイト・アプリ

- 気象庁（レーダーナウキャスト・今後の雨・２週間の雨）
- ウェザーニュース
- 天気.jp
- 釣り天気.jp
- Yahoo!天気
- Windy

## 装備品
山の事故で恐れるべきことは

1. 低体温症
1. 熱中症
1. 滑落
1. 毒

主にこの４つである。

### 山の服装
#### 雨具・靴
上下分離型のカッパを用意する。一昔前はGORE-TEXのあるカッパがある方がよかった。しかしGORE-TEXは汗で加水分解されやすく耐久性が低く、フィールドワークで毎日着用することを前提に作られていない。最近はGORE-TEXと遜色ない防水性や透湿性・耐久性が優れたカッパが販売されている。

靴はGORE-TEX製の方が調査中のQOLが圧倒的に高い。たとえ足が沢の水で濡れてもすぐに乾燥し足が蒸れない、かじかまない。そのため、快適に調査することができる。

しかし、海外の調査地ではスワンプと呼ばれる沼地を歩く必要がある。そのようなところでは長靴で調査したほうが良い。日本野鳥の会が販売している長靴は高くて破れやすいが、コンパクトに折りたためて飛行機の荷物でかさばらないし、歩きやすい。

### ライト
夕方帰る時に暗くなることや天気が悪く視界が狭くなることがある。ライトは両手を空けて歩けるように懐中電灯ではなく、**ヘッドライトを必ず携行**すること。



