# 調査地での安全対策
安全第一。**安全がデータより何よりも優先される**ことを肝に銘じよう。

野生動物の調査地では山に入って調査することも少なくないだろう。本章では、事故を未然に防止するための基本事項についての動画を紹介することで、事故をできるだけ起こさないようにすることを目指す。身の安全確保は調査での最重要ミッションである。<br>
筆者がヤクザル調査隊^a^でよく言われたのは、

- 一に安全
- 二にデータ
- 三に楽しいこと

である。<br>
大事なことなのでもう一度。安全がデータより何よりも優先されることを肝に銘じよう。<br>

フィールワークでも安全対策については日本生態学会が定期的に情報を更新している和文論文[@esj2019]がある。
全般的な安全対策については日本生態学会の和文論文に譲り、本章では特に和文論文では紹介されていない、動物を追跡するフィールドワークを必要とする研究者が、**事故予防の観点から**安全対策を行う際の必須項目について取り上げる。<br>

事故を起こさないことが何よりも重要である。しかし、自然相手にゼロリスクはありえず、山を歩いていれば小さな怪我はつきもの。そのような小さな怪我でもどのような状況で怪我したのか周りの人と情報共有することが周りの人の安全だけでなく、自分の安全にもつながる。

---

a. ヤクザル調査隊：屋久島の中腹部で行われているニホンザルの調査。毎年全国の大学生がボランティアで参加する。

## 山歩き
国立登山研修所が『新・高みへのステップ』、『安全で楽しい登山を目指して～高等学校登山指導者用テキスト』をデジタルテキストとして発行している。基礎的な山歩き、読図、ロープワークなどが学べるので必要な部分を一読してみるとよい。これはフィールドワークのみならず、震災時などの非常事態でも役に立つ。頭を使わずとも、体が勝手に動くレベルまでにしておくことが大切。

---

フィールドワークは体が資本の研究である。そのため、山を歩ける心身ともに健康な状態であることは研究をする上での第一条件になる。しかし、山を歩けることよりも大事なことは、

- ケガや事故を起こすイメージをもてること

である。
これができるのかどうかを確認する簡単な方法は、自転車・バイク・車の運転である。車の運転で事故を起こしやすい人はフィールドワークでも事故を起こしやすいのではないか、と自戒し今一度確認してほしい。<br>
その理由として、

1. 楽観的な判断をしていないか 
1. 自分の判断に自信がない（すぐに他人の判断を仰ぐ、頼る）
1. 周辺情報を見落としている（視野が狭くなっている）

ことなどが挙げられる。<br>
自分だけしっかりできていても、相手がいて周辺状況が常に変わるような環境では警戒心を持ちつつ心に余裕がないといけない。これは街中であろうが山の中だろうが変わらない。<br>
調査中は疲労蓄積もあり、なおのこと頭が鈍ってくるし、視野が狭くなる時がある。そのようなとき、楽観的に考えず、積極的に休息をとることを考えてほしい。調査目的上、自分で休息日を作れない人は尚更、注意する必要がある。
自分の見え方、感じ方、頭の動き方の変化に気づくことは、体調管理はかりでなく、生きるうえでの必須能力である。


登山に関する運動生理学の本[@yamamoto2024]があるので、必要栄養量、怪我の要因などについて確認する意味でも一度読んでみるといいだろう。

### 疲れない歩き方
疲れない歩き方は安全につながるので、普段どういう歩き方をしているのか確認しよう。 <br>
山歩きの時は腕を振らない。これはまさに「[ナンバ歩き](https://www.youtube.com/watch?v=gsUzpJNtl3M)[@nambawalk]」と呼ばれている歩き方である。へその下あたりにあると言われる丹田を意識した体の重心がぶれない歩き方は筋肉を使うことなく、疲れない歩き方である。習い事で武術を経験したことがある人は納得するだろう。

登山での疲れない歩き方について、日本山岳協会公認山岳ガイドの内田修市氏が非常にわかりやすく説明している。ここでもやはり基本は、丹田であり、重心をブレさないことである。


[登山実践講座2：登りの基本](https://youtu.be/wxiA6ZT-JrI)[@yamatabilesson2]<br>
[登山実践講座3：下りの基本](https://youtu.be/e2ExIhIiM4I)[@yamatabilesson3]<br>
[登山実践講座4：階段の上り下り](https://youtu.be/Bd4M1b-Yx_w)[@yamatabilesson4]<br>
[登山実践講座5：楽な段差の上り下り](https://youtu.be/-4_qGphpVmw)[@yamatabilesson5]<br>

### けがをしないようにするには 
運動部経験者は平地で筋肉を使う体の使いかたに慣れているせいで、起伏のある山の歩き方ができていないことがある。長期調査するに堪える持続可能な疲れにくい・けがしにくい体の使いかたを知ることは安全対策に直結し、体の余裕は心の余裕となり、観察の質向上にも十分つながりうる。

登山の運動生理学では、次の3つの指標、

1. 主観強度（心理的指標）    
1. 心拍数（生理学的指標）  
1. 登高速度（物理的指標）

を使うことで疲れにくいように工夫できることが知られている。

#### 筋肉痛
山登りでは、坂を下る際に太伸び切った太ももの前側が筋損傷することで筋肉痛が生じやすい。そのため、膝を伸ばし切らず曲げた状態を維持して下ると筋肉痛が生じにくい。一方登りでは無理な速度で歩かない限り筋肉痛にはならない。山で事故が起こるのは、転倒、転落、滑落など下りが圧倒的に多い。

##### 自分の体の状態を可視化する
自分の体の状態を可視化することで、次に向けて改善するのに役立つ。

##### 筋骨格系と神経系の連動
疲れにくい・けがしにくい身体の動かし方は筋トレして筋肉をつければいいという簡単な話ではなく、筋骨格系と神経系の連動が大切になる。これを考える際に最近の体育学の知見を紹介している[【東大式】運動能力の高め方](https://www.youtube.com/@todai_quality_of_motion)というYouTubeチャンネルでの筋骨格系と神経系との連動の話[@todai_qom231230]^,^[@todai_qom240103]が役立つだろう。

ハンマー投げの室伏広治氏の考えも参考になるかもしれない。 
自分の身体の状態を確認する「セルフチェック」の項目と動画が公開されている（[室伏広治の身体診断「セルフチェック＋改善動画」](https://www.mext.go.jp/sports/b_menu/sports/jsa_00040.html)）。自分の身体のどこに柔軟性が欠けているのかを確認し、どういうけがをしやすい状態なのかを把握することはけが防止の第一歩。

[室伏広治の個人サイト](https://kojimurofushi.net/)もあり、新聞紙や紙風船を使ったトレーニング（[動画](https://kojimurofushi.net/rt_category/training/)）等自身の研究成果について紹介している。室伏広治氏はランダムな動きを取り入れ、毎回同じ筋骨格系と神経系が使われないように工夫することで、身体能力の向上を考案しようと模索している。

学者やトレーナー、現役引退選手のみならず現役メジャーリーガーの前田健太も同様である[@maeken]。毎回同じ動きをせず、違う動きをすることで自身の体や体の軸のずれをチェックしたり、どのような体の動きでも自分のタイミングを見つけようとしている。

以上のことから考えると、繰り返し同じ動作をすることはかえって体のセンサーを鈍らせているかもしれないことは一考に値するだろう。軸を意識することで筋肉だけに頼らない体の動かし方、自分の体の理解につながるだろう。

##### 足底腱膜炎
足裏が痛くなることが多い人もいるかもしれない。為末大がYouTubeで足底腱膜炎に対処する対処と予防法について解説している[@tamesue_sokuteikenmakuen]。

#### 栄養補給
日常生活では、炭水化物、タンパク質、脂肪、ビタミン、ミネラルの5大栄養素が重要になる。しかし、登山中は特に、水分、炭水化物、塩分が重要な栄養素になる。

##### 水分・塩分
水分補給量のちがいが体温上昇に影響することが知られている[@pitts1944]。水分と塩分は1時間おきに失われた分だけ摂取すると体温上昇を防ぎ、運動を続けることができる。水分だけをとると、血中塩分濃度が下がってしまい、体が水分不足にもかかわらず体外に水分を排出してしまうことがあるため、ポカリスエットのような体組成に近い飲み物か、[塩分チャージタブレット](https://www.kabaya.co.jp/catalog/chargetablets/enbun/)を水や麦茶と一緒に摂取するとよい。

水分不足によるリスクには次が挙げれられる[@yamamoto2016]。

1. 熱中症のリスク増加
1. 心拍数増加による心臓への負担
1. 血液粘性増加による心筋梗塞や脳卒中のリスク増加
1. 持久力・筋力が低下し、疲労しやすい
1. 脳神経系の機能低下による認知能力の低下
1. 体のむくみ

熱中症の症状は次の表のように分類される[@tozankenshujo2022]。

|分類　| 症状　|症状から見た診断　|処置　|重症度|
|:--:|:------------:|:---:|:-------:|:--:|
|Ⅰ度  |めまい、立ち眩み、生あくび<br>大量の発汗、筋肉痛、こむら返り|熱痙攣、熱失神|応急処置と見守り|軽|
|Ⅱ度|頭痛、嘔吐、倦怠感、虚脱感、<br>集中力と判断力の低下|熱疲労|医療機関への搬送|中|
|Ⅲ度 |意識障害、小脳症状、痙攣発作、肝・腎臓機能症状、血液凝固異常|熱射病|医療機関で入院加療|重|

##### 朝食によるパフォーマンスへの影響
**朝食を抜くと血糖値の低下により、1時間を超えるときつく感じ、2時間ほどで運動続行が不可能**になる[@yamamoto2000]。運動パフォーマンスに雲泥の差が現れる。この研究では、缶ジュース1本を飲むと急速に血糖値が回復し、再び運動ができるようになる結果も出ている。

**どんな事情があっても必ず朝食は食べてから調査しよう。**

##### 炭水化物と脂肪
脂肪は炭水化物と比べて貯蔵量が多いが、単独では燃やすことができず、炭水化物を必要とする。また、激しい運動では燃えにくいといった特徴がある。一方で、炭水化物は単独で燃やすことができ、激しい運動にも対応できる[@yamamoto2016]。そのため、**行動食**（山歩き中定期的に補給する食べ物）を摂取する際は、適量の炭水化物（おにぎり、ビスケット、果汁グミ、チョコレートなど）を**定期的に補給**することで運動し続けることが可能となる。

炭水化物が不足すると、筋肉などに必要なたんぱく質を分解してしまう。そのうえ、たんぱく質の分解は腎臓に負担がかかるため体に良くない。

運動後は、損傷した筋肉を補修するためにたんぱく質や脂肪の積極的な補給を心がける。

炭水化物不足によるリスクには次が挙げられる[@yamamoto2016]。

1. 疲労、敏捷性・バランス能力の低下
1. 思考力・判断力の低下
1. 低体温症になりやすくなる
1. 代替エネルギーとして筋肉や臓器のたんぱく質が分解されてしまう
1. たんぱく質分解による腎臓への負担増加
1. 腎臓の負担増加による体のむくみ

##### エネルギーと水分の消費量
山歩き中と日常生活では消費量が全く異なることに注意する必要がある。

日常生活では
$$
エネルギー消費量(kcal)=体重(kg)\times行動時間(h)\times1　\\
脱水量(ml)=体重(kg)\times行動時間(h)\times1
$$
という算出式があり、山歩き中（軽装かつ標準的なコースタイムの場合）はこの5倍必要とする[@yamamoto2016]。しかし、あくまで目安なので、係数については経験則から判断する必要がある。

例えば、体重60㎏の人が10時間調査するとして、エネルギー消費量は60×10×5=3000kcalとなり、いかにエネルギーを消費しているかがわかるだろう。

時間の要素のほかに距離と荷物を含めた重量を考慮したより正確な登山に必要なエネルギー方程式は以下のように求められる[@nakahara2006]。

$$
\hspace{-10.5cm}エネルギー消費量(kcal)\\
\hspace{-10.5cm}= \underbrace{1.8\times行動時間(h)}_{時間の要素}　\\
+\underbrace{[0.3\times歩行距離(km)+10.0\times登りの累積標高差+0.6\times下りの累積標高差(km)]}_{距離の要素} \\
\hspace{-8.5cm}\times\underbrace{[体重(kg)+荷物(バッグ、服、靴)の重量(kg)]}_{重さの要素}
$$

この方程式は、快適な気象条件の下で歩いた場合であり、下限としてとらえて活用するとよい。

### 靴紐の結び方
山歩きでは思わぬところで紐が横枝に引っかかってしまい転倒、最悪の場合滑落の可能性もある。靴紐ひとつとっても身の安全に直結する。<br>

**靴紐の安全対策**

- ひもの輪っかを出さず、靴の中に入れる
- スパッツ（ゲイター）を履いて、ひもの輪っかを隠す
- 靴ひもが緩まない結び方をする

自分に合った緩まない靴紐の結び方をひとつマスターしよう。
以下のサイトや動画が参考になるだろう。

[登山実践講座1：靴の履き方](https://youtu.be/QSFR22tfc2g)[@yamatabilesson1]<br>
[YouTube: 輪舞曲鈴の庭](https://www.youtube.com/watch?v=ysTBZLLanfg)[@rinbukyokurin]<br>
[Website: 山旅旅](https://yamatabitabi.com/archives/151957/)[@yamatabitabi] <br>

### 登山靴の選び方
登山靴はメーカーや同じメーカーでもシリーズによって形がまったく違う。足の形は人それぞれなので、とにかくいろいろ試し履きして合う靴を探すしかない。

--- 


1. 足の角に当たらない靴を選ぶ<br>
隙間がなく足にピッタリ沿う靴がベスト。高さは中敷きで調節可能 (5000～6000円くらいするが、長く使えるのでお買い得)。革の登山靴以外は運動靴みたいになじむことはないので、最初がダメなら後もダメ。
1. 下り坂でつま先が当たらない靴を選ぶ<br>
登山店には必ず下り坂があるので、そこで足踏みしてつま先が当たらないことを確認する
1. メッシュの登山靴は選ばない<br>
岩場を歩いているとあっという間にメッシュの部分から破れてしまう。こうなってしまうと、防水機能も発揮してくれず使い物にならない。
1. ミドルカットの靴を選ぶ<br>
何もわからないならミドルカットの登山靴を選ぼう。
メリットとしては次のようなことが挙げられる。
- 足首を支えてくれる
- 砂・泥除けでスパッツ（ゲーター）を履く場合などにも必要な高さ





## 地図読み
山の中は圏外なので、地図読みは生死に直結する能力の一つであり、フィールドワークで必ず身につけなければならない。<br>
注意してほしいのは、**地図を過信しないこと**。2万5千分の1の地図で一見危険でなさそうな場所でも、現場に行くと危険な場所がある。**図よりも目の前の地形が現実**なので、地図を参考にしながら最後は**自分の感覚で危険を察知**しなければならない。

[山と渓谷オンライン](https://www.yamakei-online.com/yama-ya/detail.php?id=2335)[@yamatokeikoku_dokuzu]やYAMAP MAGAGINEの地図読みの技術｜[初心者のための基礎知識](https://yamap.com/magazine/feature/726)で読図の説明があるので、地図の読み方がわからない人は必ず読んで覚えること。 

### 地形図
まずはパソコンやタブレットで国土地理院の地図を見よう[こちら](https://maps.gsi.go.jp/#5/36.104611/140.084556/&base=std&ls=std&disp=1&vs=c1g1j0h0k0l0u0t0z0r0s0m0f1)。
最近の電子地図は山の地形がわかりやすいように影がついている。影がついていなくても地図を見て立体視できるように慣れておこう。

### GPS
調査ではGarmin社製のGPSロガーがよく使われる。<br>
よく使われるPosition formatは”UTM UPS”、Map datumは”WGS84”。Tracksは、日々の遊動域の確認で使いやすいように、Advanced Setup ＞ Auto Archiveと進み、Dailyを選択すると便利。Recording Intervalは1分くらいにすると滑らかな移動経路が地図に現れる。数分おきだと急に移動するときに汚く表示される。この間隔に関しては自身の調査計画と見た目の感覚による。

## 天気
調査中は夜翌日の天気、朝に当日の天気を確認する。山の天気は変わりやすく、雨は低体温症の原因になる。調査中雨具は携行するほうがよい。

### 天気図の読み取り


### 天気予報サイト・アプリ
天気アプリは、山を考慮せずに天気予報していることが体感的にありそう。そのため、天気が外れることはままある。<br>ただ、過去の天気情報は実データである。そのため、過去数時間の天気予報を遡り、未来の30分、1時間を予測するというやり方がある。

```{r Wheather, echo=FALSE, warning=FALSE}
library(gt)
library(gtExtras)

data.frame("アプリ" = c("気象庁", 
                        "ウェザーニュース", 
                        "天気.jp",
                        "釣り天気.jp",
                        "Yahoo!天気",
                        "Windy"),
           "Logo" = c("https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/%E6%B0%97%E8%B1%A1%E5%BA%81.svg/1280px-%E6%B0%97%E8%B1%A1%E5%BA%81.svg.png",
                      "https://pbs.twimg.com/profile_images/1605340045442879488/q96-KnC-_400x400.jpg",
                      "https://pbs.twimg.com/profile_images/940465505550266368/kRoAQOL8_400x400.jpg",
                      "https://www.tsuritenki.jp/img/main_logo.svg",
                      "https://pbs.twimg.com/profile_images/1179176831540330496/Fkk4yl_5_400x400.jpg",
                      "https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/17/60/ac/1760ac01-bf40-9359-bc78-17e2a4edf343/AppIcon-0-0-1x_U007emarketing-0-7-0-85-220.png/1200x600wa.png"),
           "備考" = c("レーダーナウキャスト・今後の雨・２週間の雨","","","港をもとにした細かい場所の天気予報がわかる","Yahoo!会員なら便利","細かい風向がわかって便利")) %>% 
  gt(caption = "代表的な天気予報アプリ") %>% 
  ##画像の挿入
  gt_img_rows(Logo, height = 35) %>% 
  ##列名の変更
  cols_label("Logo" = "ロゴ") %>% 
  gt_theme_espn() %>% 
  cols_align(align = "center")


  
```



### 落雷 

落雷についての注意喚起が気象庁で公開されている。小学生のときに防災や理科で学習したと思う。しかし、想定しないといざ実際に行動するときに迷いが生じてしまう。そのため、雷や大雨に遭ったときにどうするのか頭で整理し、身の安全を守ろう。 

- [「雷」による災害](https://www.jma.go.jp/jma/kishou/know/tenki_chuui/tenki_chuui_p4.html) 
- [雷から身を守るには](https://www.jma.go.jp/jma/kishou/know/toppuu/thunder4-3.html) 
- [防災啓発ビデオ「急な大雨・雷・竜巻から身を守ろう！」](https://www.jma.go.jp/jma/kishou/books/cb_saigai_dvd/index.html) 

## 装備品
山の事故で恐れるべきことは

1. 低体温症
1. 熱中症
1. 滑落
1. 毒

主にこの４つである。

## 危険生物 
### 日本国内
調査地にどのような危険生物がいるのか把握し、その対策を練る必要がある。
例えば、

- 野犬
- クマ
- ヘビ
- シカ

意外かもしれないが、林道を走行中の時に人の次に危ないのがシカである。シカはどういうわけか逃げようとすると、一度避けたかと思うと車やバイクに突っ込んでくる非常に恐ろしい習性がある。そのため、夜道のバイクは特にシカと接触し転倒する可能性が高まる。夜が更けても林道内は徐行するように心がける。車の時も、急に出てきたシカを避けようとハンドルを切り、森の中に突っ込みレッカーを呼ぶ羽目になったレンタカーがいる。車の時はハンドルを切らずブレーキをかけるだけに留める。 

### 海外
- 蚊（マラリア、デング熱etc.）
- ゾウ
- カバ
- ワニ
- 捕食者（ライオン、トラetc.）

### 山の服装
#### 雨具・靴
上下分離型のカッパを用意する。一昔前はGORE-TEXのあるカッパがある方がよかった。しかしGORE-TEXは汗で加水分解されやすく耐久性が低く、フィールドワークで毎日着用することを前提に作られていない。最近はGORE-TEXと遜色ない防水性や透湿性・耐久性が優れたカッパが販売されている。

靴はGORE-TEX製の方が調査中のQOLが圧倒的に高い。たとえ足が沢の水で濡れてもすぐに乾燥し足が蒸れない、かじかまない。そのため、快適に調査することができる。

しかし、海外の調査地ではスワンプと呼ばれる沼地を歩く必要がある。そのようなところでは長靴で調査したほうが良い。日本野鳥の会が販売している長靴は高くて破れやすいが、コンパクトに折りたためて飛行機の荷物でかさばらないし、歩きやすい。

### ライト
夕方帰る時に暗くなることや天気が悪く視界が狭くなることがある。ライトは両手を空けて歩けるように懐中電灯ではなく、**ヘッドライトを必ず携行**すること。


## 山での死亡事故例 

平地で転倒して死んでしまうこともある。どのような事故がありうるのか、動画（[山と渓谷ch.](https://youtu.be/VwtLsVNHBpI?si=WSiiZal1SrDsUiXU) ）だけでなく、日々調査で感じながら考え備えることが調査をするうえで必要不可欠な能力。 

  

日本生態学会誌　[安全管理マニュアル](https://www.jstage.jst.go.jp/article/seitai/69/Special_Issue/69_S1/_article/-char/ja/) [@esj2019]

日本生態学会がこれまでの事故を教訓にするように作られた安全管理マニュアル。サルを追跡する際の注意点などマイナーなことは書かれていないが、大方のことは書かれている。調査前に熟読することを強く勧める。 


